### ISSUE TITLE
Implement the .NET SDK for Casdoor

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-dotnet-sdk#1]
This is a very easy task, because all the Casdoor SDKs for different languages are very similar. So this task just requires to port the Go SDK or Java SDK to .NET. See:

- https://github.com/casdoor/casdoor-go-sdk
- https://github.com/casdoor/casdoor-java-sdk

One thing for beginer to learn is that how to develop a library in .NET, for this part, you can refer to the middlewares in Casbin.NET: https://github.com/casbin-net , you can basically get a C# library template to start with.

**Comment by hsluoyz** [comment]
@hackerchai

**Comment by hsluoyz** [comment]
Any interest on this? @rafaelgfirmino

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/casdoor/casdoor-dotnet-sdk/pull/5

**Comment by sagilio** [comment]
relate issue: https://github.com/casdoor/casdoor-dotnet-sdk/issues/2
