### ISSUE TITLE
Fix CI last build error

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-dotnet-sdk#25]
See: https://github.com/casdoor/casdoor-dotnet-sdk

![image](https://user-images.githubusercontent.com/3787410/173210255-6fed4cc2-fa21-4775-9c46-105aeaef3e0d.png)

**Comment by hsluoyz** [comment]
@AsakusaRinne @sociometry

**Comment by AsakusaRinne** [comment]
It's not a build error but a conflict caused by the branch merge. The conflict is in the ```samples/Program.cs```. @sagilio Could you please force push the last commit and solve the conflict?

**Comment by sagilio** [comment]
@hsluoyz  Github Actions network issues, retry was successful

![image](https://user-images.githubusercontent.com/42855245/173226533-092f35f9-2cec-411e-be85-f4f418ca7875.png)

**Comment by sagilio** [comment]
> It's not a build error but a conflict caused by the branch merge. The conflict is in the `samples/Program.cs`. @sagilio Could you please force push the last commit and solve the conflict?

This is the failed run log: https://github.com/casdoor/casdoor-dotnet-sdk/runs/6844834082?check_suite_focus=true
![image](https://user-images.githubusercontent.com/42855245/173226709-97fcb2df-f2a9-4a99-9cb4-487f3bb4bccd.png)

**Comment by hsluoyz** [comment]
OK
