### ISSUE TITLE
Can't set port in Casdoor url

### ISSUE THREAD

**Issue by MadL1me** [casdoor/casdoor-dotnet-sdk#37]
When using casdoor for local development, there is cases, when casdoor cannot be published on 7001 port.

I thought, it would work, if I define port in the Endpoint, like this:

![image](https://user-images.githubusercontent.com/46647517/232435350-41696e47-4a2a-49bc-8c66-a0c86a600c0b.png)

But it didn't worked, it still uses 7001 port.
How this can be avoided?

**Comment by hsluoyz** [comment]
@MadL1me hi, why close it?

**Comment by MadL1me** [comment]
@hsluoyz sorry, I mistaken that problem was fixed for me. I was tired and forget at the start of the day, that I fixed it yesterday evening by deploying Casdoor localy on 7001 port. The problem still exists

**Comment by hsluoyz** [comment]
@MadL1me please make a PR

**Comment by 2236721325** [comment]
> When using casdoor for local development, there is cases, when casdoor cannot be published on 7001 port.
> 
> I thought, it would work, if I define port in the Endpoint, like this:
> 
> ![image](https://user-images.githubusercontent.com/46647517/232435350-41696e47-4a2a-49bc-8c66-a0c86a600c0b.png)
> 
> But it didn't worked, it still uses 7001 port. How this can be avoided?

May be you should clear your browser's cookies and run it again.

**Comment by hsluoyz** [comment]
@MadL1me did you restart the MVC application and reload the page? The changes in `appsettings.json` should have taken effect after you refresh the web page in browser

![T$E}$9~$QS}430TE%Z8CGQ](https://github.com/casdoor/casdoor-dotnet-sdk/assets/3787410/3f7e7a1a-51c9-4d02-a652-5cdfd87d9d97)

**Comment by hsluoyz** [comment]
Closed as resolved
