### ISSUE TITLE
Uninformative unauthorized error in API client

### ISSUE THREAD

**Issue by MadL1me** [casdoor/casdoor-dotnet-sdk#38]
In some cases when using Casdoor Api client, you can find uninformative errors, like these:

![image](https://user-images.githubusercontent.com/46647517/233650526-8f124333-e15c-4363-b031-dd8c517eee42.png)

The error says, that issue is json parsing, but if you log http message request/response, you'll see that the main reason why code failed, is "Unauthorized operation": 

![image](https://user-images.githubusercontent.com/46647517/233650616-5e3cc4ef-fa7d-4365-b480-1879a1ea7456.png)

This happens, if you forget about setting up token in client or you have invalid configuration file (for example, organization-owner does not exists with this name, invalid url, etc), and error does nothing to address that.

**Comment by hsluoyz** [comment]
@MadL1me hi, can you make a PR to fix it?

**Comment by MadL1me** [comment]
> @MadL1me hi, can you make a PR to fix it?

Yep
