### ISSUE TITLE
Fix the semantic-release and auto release new versions

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-dotnet-sdk#43]
After PR: https://github.com/casdoor/casdoor-dotnet-sdk/pull/41 is merged, new release doesn't come out, need fix

**Comment by zabbius** [comment]
hi, don't understand the problem, could you please tell me what to fix

**Comment by zabbius** [comment]
Am I right that problem is no in merged code but in current guthub workflow settings?

**Comment by hsluoyz** [comment]
@zabbius yes, we want to make the CI auto release each PR into nuget

**Comment by sagilio** [comment]
In order to worry about the release of versions that are not available during development, the release workflow has been set to the manual release before.
I think it is no longer necessary now, so I have created a [PR](#44) to adjust it.
