### ISSUE TITLE
How to import Casdoor.Client into Unity 3D project?

### ISSUE THREAD

**Issue by Wrapping-2000** [casdoor/casdoor-dotnet-sdk#60]
When I am making a Unity 3D mobile game, I need to use the Casdoor.Client package, but when I try to import this Casdoor.Client using the URL, it fails.

My code is: https://github.com/casdoor/casdoor-unity-example/pull/2

<img width="823" alt="截屏2023-08-12 11 42 12" src="https://github.com/casdoor/casdoor-dotnet-sdk/assets/110087455/02e995b5-4911-41b5-9c72-20c2f67f9f33">
<img width="823" alt="截屏2023-08-12 11 43 14" src="https://github.com/casdoor/casdoor-dotnet-sdk/assets/110087455/73948bc3-8330-4f8a-9711-a6414dafb9a5">

My current import method is to download and run casdoor-dotnet-sdk, and then copy the net462 folder under the Debug folder to the project. This is feasible, but it does not meet the development specifications.

Can you support using URL import? Or is there something wrong with the way I import it? Please advise me.

**Comment by Tanyuu** [comment]
In my cursory testing, neither HTTPS nor SSH from github succeeded in fetching the package. But I found a third party Nuget package manager that supports Unity: [A Chinese Blog](https://blog.walterlv.com/post/third-party-unity-nuget-management.html)
After installing it following the steps on the blog, I was able to get Casdoor.Client correctly and develop it.
![image](https://github.com/casdoor/casdoor-dotnet-sdk/assets/75737870/7d9c38bb-b574-4c69-beb9-8f9fd8f7ba13)
Next I'll consider how to add packages via url, and the necessity of not adding packages in an incidental way (but via url).

**Comment by Wrapping-2000** [comment]
Get it.Thank you. @Tanyuu

**Comment by Tanyuu** [comment]
Well, unity packages imported from the git url also need to come with a package.json file to store dependencies and such, and our Casdoor is dependent on the .csproj file. If you want to import packages via disk or url, you might need to make some kind of conversion of our packages (create package.json). But it seems unnecessary at the moment, and NuGetForUnity is a suitable route.
Here's a similar question I found: [Why can't I include RestSharp in my Unity project?](https://stackoverflow.com/questions/71482903/why-cant-i-include-restsharp-in-my-unity-project)

**Comment by Tanyuu** [comment]
If we want to install from giturl, we can follow this tutorial. [Install a package from a Git URL](https://docs.unity3d.com/2021.3/Documentation/Manual/upm-ui-giturl.html) However, packages in git need to be defined according to this package layout [Package layout](https://docs.unity3d.com/2021.3/Documentation/Manual/cus-layout.html) - but Casdoor .NET development does not follow the Unity definition.

**Comment by hsluoyz** [comment]
Resolved
