### ISSUE TITLE
There is no changes in sdk v1.7.0

### ISSUE THREAD

**Issue by d1mak3** [casdoor/casdoor-dotnet-sdk#70]
Hi! I tried to use methods that were added but there was none of them

**Comment by hsluoyz** [comment]
@d1mak3 you added the code, so why?

**Comment by d1mak3** [comment]
> @d1mak3 you added the code, so why?

I mean, the code works fine when I use it in sdk's example project. But it does not when I use it from nuget package. I think it might be some build issues

**Comment by d1mak3** [comment]
So, for example, method
```
public virtual async Task<IEnumerable<CasdoorRole>?> GetRolesAsync(string? owner = null, CancellationToken cancellationToken = default)
```
In Casdoor.Client v1.7.0 nuget package still looks like
```
public virtual async Task<IEnumerable<CasdoorRole>?> GetRolesAsync(CancellationToken cancellationToken = default)
```
Like it was in v1.6.0 although it's been changed

**Comment by sagilio** [comment]
> @sagilio any clue for this?

The package be pushed at this action: https://github.com/casdoor/casdoor-dotnet-sdk/actions/runs/6032219356/job/16367150639. So the behind pushes package failed because the version already exists.
The reason is that 3 release actions are executed at the same time.

**Comment by sagilio** [comment]
v1.8.0 is healthy.
