### ISSUE TITLE
IDX20803: Unable to obtain configuration from: 'http://localhost:7001/.well-known/openid-configuration'.

### ISSUE THREAD

**Issue by wuxiao-ling197** [casdoor/casdoor-dotnet-sdk#91]
![1](https://github.com/casdoor/casdoor-dotnet-sdk/assets/77096395/fb362cdf-e33d-46eb-8656-2e2f957abf00)

![2](https://github.com/casdoor/casdoor-dotnet-sdk/assets/77096395/cfad87c0-fdc4-432e-98d3-a8652ce067ed)

hello , this is what my error . I only changed the CasdorOptions params and then just run this ConsoleApp program , it told me  I can`t get the configuration ; but if I run it in MVCApp it was success , and I have try to deploy casdoor in public domain like https://xxx.com but I have any idea how to achieve it , Thank you ver much !

**Comment by hsluoyz** [comment]
@wuxiao-ling197 you should deploy Casdoor in Production mode: https://casdoor.org/docs/basic/server-installation/#production-mode (yarn build) and use endpoint: `http://localhost:8000`

![image](https://github.com/casdoor/casdoor-dotnet-sdk/assets/3787410/74650464-cd63-4557-b391-08634327a65e)

**Comment by hsluoyz** [comment]
@wuxiao-ling197 pull latest code, fixed by: https://github.com/casdoor/casdoor-dotnet-sdk/commit/38ee767d66fd267d0b1bc7f98e6e4295f0725362

**Comment by robincodex** [comment]
I'm getting the same error, I've debugged and found that the conditional `(_syncAfter <= now)` judgment here is false, is there anything else I need to do?

```cs
var t = await client.RequestClientCredentialsTokenAsync();
```
```
console  |       System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://casdoor:8000/.well-known/openid-configuration'.
console  |          at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.GetConfigurationAsync(CancellationToken cancel)
console  |          at Casdoor.Client.CasdoorClient.ApplyConfigurationAsync[T](T request, CancellationToken cancellationToken)
console  |          at Casdoor.Client.CasdoorClient.RequestAuthorizationCodeTokenAsync(String code, String redirectUri, String codeVerifier, CancellationToken cancellationToken)
console  |          at Studio.Console.Controllers.UnauthorizedUserController.SignIn(String code, String state)
```

![image](https://github.com/user-attachments/assets/f3c6c0a8-20bb-4fa5-b05c-5946a13dbc84)
